server:
  port: 9005
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
spring:
  ai:
    dashscope:
      api-key: ${ali-bailian-ak}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen-plus
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3
      timeout: 2
wisps:
  model: deepseek-v3.1
  t2i: wan2.5-t2i-preview


