server:
  port: 9007
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  ai:
    dashscope:
      api-key: ${ali-bailian-ak}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          #          model: qwen-plus
          model: deepseek-v3.1