server:
  port: 9008
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
spring:
  ai:
    openai:
      api-key: ${ali-bailian-ak}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
#          model: qwen-plus
          model: deepseek-v3.1