server:
  port: 9004
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
spring:
  ai:
    dashscope:
      api-key: ${ali-bailian-ak}
      chat:
        options:
          model: deepseek-v3.1
      embedding:
        options:
          model: text-embedding-v4
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
  data:
    redis:
      host: localhost
      port: 6379
      database: 0